bnb-chain/greenfield-docs

src/guide/resources.md
Fix a typo, and add correct wording
Correct wording so user can read it the message better
=> Fix typo and add correct wording

src/guide/storage-provider/run-book/run-testnet-SP-node.md
remove the validator vote command in the runbook of sp testnet
it is misleading.
=> feat: remove the validator vote step in the runbook of sp testnet

src/guide/concept/simple-storage-svc-model.md, src/guide/greenfield-blockchain/modules/storage-module.md
Update latest proto message
the current proto message is out of date.
=> fix: update latest proto message

src/guide/dapp/contract-list.md, src/guide/dapp/overview.md, src/guide/dapp/primitive-interface.md
The dapp contains too many code based docs, we try to improve it to add readability.
1. Give the contract address list on BSC testnet;
2. Give a prototype design of data marketplace.
=> docs: refine the docs of dapps

src/guide/dapp/primitive-interface.md
This PR gives a detailed introduction about the permission module on BSC smart contract
Add more docs about dapp interface.
=> docs: add permission module docs for dapp

src/guide/storage-provider/run-book/run-testnet-SP-node.md
=> docs: fix some wrong commands

src/guide/README.md, src/guide/storage-provider/run-book/run-local-SP-network.md
we add a script to export all the keys of sp to help user start local network quickly.
https://github.com/bnb-chain/greenfield/pull/180
improve user experience
=> docs: update localup runbook

src/guide/dapp/contract-list.md, src/guide/dapp/dapp-integration.md, src/guide/dapp/quick-start.md
Add a step-by-step tutorial about app, so the developer can have a concrete feeling before integration.
Improve the guide of dapp.
=> docs: add a more easy dapp tutorial

src/guide/storage-provider/services/metadata.md
fix a wrong term in metadata doc
N/A
=> fix: avoid to use a stale term

src/api-sdk/storgae-provider-rest/common/readme.md, src/api-sdk/storgae-provider-rest/get_approval.md, src/api-sdk/storgae-provider-rest/get_object.md, src/api-sdk/storgae-provider-rest/get_user_buckets.md, src/api-sdk/storgae-provider-rest/list_bucket_read_records.md, src/api-sdk/storgae-provider-rest/list_objects_by_bucket.md, src/api-sdk/storgae-provider-rest/put_object.md, src/api-sdk/storgae-provider-rest/query_bucket_read_quota.md, src/api-sdk/storgae-provider-rest/referenece/gnfd_headers.md, src/api-sdk/storgae-provider-rest/referenece/readme.md, src/api-sdk/storgae-provider-rest/referenece/virtual_hosting_of_buckets.md, src/guide/storage-provider/run-book/run-local-SP-network.md
Add sp header, virutal-hosted-style and path-style docs.
N/A
=> docs: add sp header, virutal-hosted-style and path-style docs

src/guide/concept/transaction-lifecycle.md, src/release-note/README.md
Add release note for greenfield v0.1.2
We has released the new version and upgraded it to testnet, so we should update the docs.
=> Release note for greenfield v0.1.2

src/guide/dapp/contract-list.md
update new greenfiled contract addresses on testnet
=> feat: update greenfield contracts on testnet

src/guide/storage-provider/run-book/compile-dependences.md
Fix protobuf compiler to cosmos/gogoproto
N/A
=> docs: fix protobuf compiler to cosmos/gogoproto

src/guide/concept/programmability.md, src/guide/greenfield-blockchain/modules/cross-chain.md
This PR just refine some wording of the docs.
Refine the wording.
=> doc: refine the wording

src/guide/storage-provider/run-book/run-testnet-SP-node.md
Add gc account generated command
The gc account generated command missing.
=> docs:fix gc accout

src/guide/getting-started/interact-with-greenfield.md
update cmd doc with new command tool version
the subcommand usage has been changed
=> doc: update cmd doc with new version

src/guide/storage-provider/run-book/run-testnet-SP-node.md, src/guide/storage-provider/services/stopserving.md
This pr adds more information for stop serving service.
Update document
=> docs: update documents for stop serving service

src/api-sdk/storgae-provider-rest/get_user_buckets.md, src/api-sdk/storgae-provider-rest/list_objects_by_bucket.md, src/guide/storage-provider/run-book/run-testnet-SP-node.md
update listobjects folder and pagination new feature
added new parameter in listobjects
=> docs: update listobjects

src/guide/dapp/contract-list.md, src/guide/resources.md
Few modification according to the new testnet
As we launch the new gnfd test, we need to update the resouce page and also the contract endpoints.
=> docs: update the resource and contract list for new gnfd testnet

src/api-sdk/endpoints.md, src/guide/greenfield-blockchain/run-node/become-testnet-validator.md, src/guide/greenfield-blockchain/run-node/run-local-network.md, src/guide/greenfield-blockchain/run-node/run-testnet-node.md, src/guide/storage-provider/run-book/run-testnet-SP-node.md
fix docs to adapt to v0.2.1 testnet
Greenfield testnet has been reset and upgraded to v0.2.1 on 2023/5/25
=> docs: fix docs to adapt to v0.2.1 testnet

src/guide/dapp/quick-start.md
This pr is to update the `quick start` part.
This part of doc is out of date
=> docs: update quick-start.md

src/guide/getting-started/get-test-bnb.md
add doc about cross-chain transfer from BSC to greenfield
=> feat(cross-chain): add doc about cross-chain transfer from BSC to greenfield

src/guide/getting-started/interact-with-greenfield.md
update greenfield cmd doc with new version
need update usage
=> docs: update greenfield cmd doc

docs/api-sdk/storgae-provider-rest/list_buckets_by_bucket_ids.md, docs/api-sdk/storgae-provider-rest/list_objects_by_object_ids.md, sidebars.js
add docs for list object by object ids and list buckets by bucket ids
=> docs: list objects and buckets

docs/api-sdk/README.md, docs/api-sdk/storgae-provider-rest/readme.md, docs/guide/concept/readme.md, docs/guide/dapp/README.md, docs/guide/getting-started/README.md, docs/guide/greenfield-blockchain/README.md, docs/guide/greenfield-blockchain/modules/readme.md, docs/guide/greenfield-blockchain/overview.md, docs/guide/greenfield-blockchain/run-node/readme.md, docs/guide/storage-provider/README.md, docs/guide/storage-provider/cli/readme.md, docs/guide/storage-provider/introduction/readme.md, docs/guide/storage-provider/run-book/readme.md, docs/guide/storage-provider/services/readme.md, docusaurus.config.js
removed extra readme files to improve search indexing
=> Removed extra readme files

docs/guide/storage-provider/services/piece-store.md, docs/guide/storage-provider/services/uploader.md
- Added configuration details when using MinIO as your storage system.
- Added mention that Multipart Upload are not yet supported, but will be implemented in the future.
=> MinIO config | Multiupload details

docs/guide/resources.md
This PR just refine the description of  Dcellar and redirect to more of the docs related with dcellar
=> docs: add rich dcellar description

docs/guide/storage-provider/run-book/config.md, docs/guide/storage-provider/run-book/run-local-SP-network.md, docs/guide/storage-provider/run-book/run-testnet-SP-node.md
add instruction on how to prepare bls pub key and bls proof to create storage provider
=> WIP: add instruction regrading storage provider config BLS key

docs/guide/storage-provider/run-book/config.md, docs/guide/storage-provider/run-book/run-local-SP-network.md, docs/guide/storage-provider/run-book/run-testnet-SP-node.md
Reverts bnb-chain/greenfield-docs#123
=> Revert "WIP: add instruction regrading storage provider config BLS key"

docs/guide/dapp/showcases.md
This PR just fix the wrong format of the showcase page.
As described
=> docs: fix the wrong format of showcase

docs/guide/greenfield-blockchain/cli/challenge.md, sidebars.js
adds a guide for challenger  
it helps the user to interact with the challenger module
=> docs: adding a guide for challenger

docs/guide/greenfield-blockchain/run-node/become-testnet-validator.md, docs/guide/greenfield-blockchain/run-node/run-testnet-node.md, docs/guide/greenfield-blockchain/run-node/run-testnet-relayer-and-challenger.md, sidebars.js
This pr is to add a guide for running relayer and challenger on testnet
It helps to run relayer and challenger which are necessary for being a validator
=> docs: add guide for running relayer and challenger on testnet

docs/guide/storage-provider/run-book/run-testnet-SP-node.md
=> fix:blocksyncer db config

docs/api-sdk/storgae-provider-rest/get_bucket_meta.md, docs/api-sdk/storgae-provider-rest/get_group_list.md, docs/api-sdk/storgae-provider-rest/get_object_meta.md, docs/api-sdk/storgae-provider-rest/get_user_buckets.md, docs/api-sdk/storgae-provider-rest/list_buckets_by_bucket_ids.md, docs/api-sdk/storgae-provider-rest/list_objects_by_bucket.md, docs/api-sdk/storgae-provider-rest/list_objects_by_object_ids.md, docs/api-sdk/storgae-provider-rest/verify_permission.md
1. remove metadata v2
2. add remove filter for list objects & list buckets
N/A
=> feat: list removed and remove v2

docs/guide/core-concept/billing-payment.md, docs/guide/greenfield-blockchain/modules/billing-and-payment.md
This pr updated payment document to align the current implementation.
* align new changes
=> docs: update payment docs based on recent changes

docs/contribute.md, docs/release-notes/releaseNotes.md, sidebars.js
prepare for testnet reset
add changelog and add resource link
=> Add changelog

docs/api/blockchain-cli/challenge.md, docs/guide/greenfield-blockchain/modules/billing-and-payment.md
This pr updates the content of challenge cli document, and fix an issue in payment document.
fix documents
=> docs: update challenge cli document and fix payment document

docs/guide/dapp/contract-list.md
=> docs: update testnet contract addr

docs/guide/core-concept/gas-fees.md
=> docs: update gas-fee list

docs/tutorials/dapp/showcases.md
Update the datamarketplace to latest version
=> docs: update latest data markeplace link

docs/guide/storage-provider/run-book/common-issues.md, docs/guide/storage-provider/run-book/config.md
Modified the config related to blocksyncer
1. add new modules
2. DSN configuration was modified
adapt the new code version
=> fix:blocksyncer config

docs/guide/storage-provider/run-book/common-issues.md
Edit common issues
SP binary does not use P2P protocol in this version
=> remote p2p bootstrap url

.github/ISSUE_TEMPLATE/question.md
=> chore: add issue template

docs/guide/greenfield-blockchain/run-node/run-testnet-relayer-and-challenger.md
add instruction for export keys of relayer and challenger 
=> docs: instruction for export relayer and challenger keys

docs/api/storgae-provider-rest/get_bucket_meta.md, docs/api/storgae-provider-rest/get_group_list.md, docs/api/storgae-provider-rest/get_object_meta.md, docs/api/storgae-provider-rest/get_user_buckets.md, docs/api/storgae-provider-rest/list_buckets_by_ids.md, docs/api/storgae-provider-rest/list_group_members.md, docs/api/storgae-provider-rest/list_objects_by_bucket.md, docs/api/storgae-provider-rest/list_objects_by_ids.md, docs/api/storgae-provider-rest/list_user_groups.md, docs/api/storgae-provider-rest/list_user_owned_groups.md, docs/api/storgae-provider-rest/verify_permission.md, sidebars.js
1. replace all metadata json response to xml
2. add ListUserOwnedGroups/ListUserGroups/ListGroupsMembers
3. replace listobjectsbyids and listbucketbyids from post to get
N/A
=> docs: replace json to xml

docs/guide/storage-provider/introduction/workflow.md, docs/guide/storage-provider/run-book/run-local-SP-network.md, docs/guide/storage-provider/run-book/run-testnet-SP-node.md, docs/tutorials/dapp/contract-list.md, docs/tutorials/dapp/dapp-integration.md, docs/tutorials/dapp/permission-control.md, docs/tutorials/dapp/primitive-interface.md, docs/tutorials/dapp/quick-start.md, docs/tutorials/dapp/showcases.md, sidebars.js
1. Update the structure of "Tutorial'
2. all the modules should have hyperlink to workflow page
3. add a summary or guide page at the beginning
Improve doc quality
=> update docs based on feedbacks

docs/guide/core-concept/storage-provider-lifecycle.md, docs/guide/greenfield-blockchain/modules/storage-provider.md, docs/guide/storage-provider/run-book/run-local-SP-network.md, docs/guide/storage-provider/run-book/run-testnet-SP-node.md
add sp maintenance mode instruction
=> doc: sp maintenance mode instruction

docs/tutorials/native-dapp/sdk/file-management/overview.md
The formatting was broken in the golang examples, making it impossible to copy the examples into the IDE. Also added syntax highlighting.
Give developers the ability to use examples without problems. Otherwise it seems that the product is broken.
=> fix golang examples in docs

docs/guide/storage-provider/run-book/run-testnet-SP-node.md
add more instruction for maintenance mode
=> docs: add more instruction for maintenance mode

docs/guide/core-concept/simple-storage-service.md, docs/guide/storage-provider/modules/p2p.md, docs/guide/storage-provider/run-book/config.md, docs/tutorials/native-dapp/sdk/resumable-upload/overview.md
=> docs: add more for bucket migrate & p2p

docs/api/storgae-provider-rest/README.md, docs/api/storgae-provider-rest/get_nonce.md, docs/api/storgae-provider-rest/update_key.md, docs/guide/storage-provider/introduction/standard.md, docs/guide/storage-provider/modules/authenticator.md, docs/guide/storage-provider/modules/gateway.md, docs/guide/storage-provider/run-book/common-issues.md
update auth related docs to match the latest auth implementation after refactoring
adapt to v0.2.4
=> feat: auth doc

docs/guide/storage-provider/run-book/piece-store.md
Update piecestore oss docs.
N/A
=> docs: update piecestore oss docs

docs/tutorials/dapp/contract-list.md
=> fix: update contract entrypoint

docs/api/storgae-provider-rest/query_bucket_read_quota.md, docs/guide/getting-started/greenfield-command.md, docs/guide/storage-provider/run-book/run-local-SP-network.md
=> docs: fix quota api and cmd

docs/tutorials/dapp/contract-list.md
=> feat: update contract list

docs/tutorials/dapp/dapp-integration.md
This pr is to update dapp contracts sdk's description
To be align with the newest contract sdk version
=> docs: update dapp contracts sdk

docs/tutorials/dapp/quick-start.md, docs/tutorials/dapp/showcases.md
This pr is to update quick-start tutorial and data marketplace demo link
update quick-start tutorial and data marketplace demo link
=> docs: update quick-start tutorial and data marketplace demo link

docs/sdks/sdk-js.md
Update new document for js sdk
none.
=> docs: Update js doc

docs/sdks/sdk-go.md
update `greenfield-go-sdk` documentation
=> docs: update sdk docs

docs/guide/greenfield-blockchain/modules/billing-and-payment.md
Add document for large amount withdrawal from payment account.
Refine documents
=> docs: add docs for withdraw timelocker

docs/release-notes/releaseNotes.md
Add the release note for v0.2.5 and v0.2.6
No
=> add release note for v0.2.6

docs/guide/storage-provider/run-book/piece-store.md, docs/guide/storage-provider/run-book/run-local-SP-network.md
Fix PieceStore of SP runbook.
N/A
=> docs: fix sp run book about piece store

docs/guide/storage-provider/run-book/run-testnet-SP-node.md
Refine database config section:
=> fix:create database doc

docs/guide/greenfield-blockchain/run-node/run-testnet-relayer-and-challenger.md
update relayer example smart contract address
=> docs: update relayer example smart contract address

docs/api/storage-provider-rest/get_bucket_meta.md, docs/api/storage-provider-rest/get_user_buckets.md, docs/api/storage-provider-rest/list_groups_by_ids.md, docs/api/storage-provider-rest/list_user_payment_accounts.md, docs/api/storage-provider-rest/list_user_payment_streams.md, sidebars.js
update metadata payment apis & bucket response
N/A
=> docs: update metadata payment apis & bucket response

docs/guide/greenfield-blockchain/run-node/run-testnet-relayer-and-challenger.md
=> docs: add note for using BSC RPC

docs/guide/storage-provider/introduction/overview.md, docs/guide/storage-provider/introduction/standard.md, docs/guide/storage-provider/introduction/workflow.md
=> docs: fix sp introduction dir

docs/api/storage-provider-rest/README.md
Refine auth doc 
1. adding desc for `X-Gnfd-Expiry-Timestamp` header when generating the authorization header
2.  correct the hash process for canonical request.
=> docs: refine auth by adding desc for `X-Gnfd-Expiry-Timestamp` header

docs/guide/getting-started/greenfield-command.md
=> docs: upgrade greenfield commands doc

docs/api/blockchain-cli/README.md, docs/api/blockchain-cli/bank.md, docs/api/blockchain-cli/bridge.md, docs/api/blockchain-cli/challenge.md, docs/api/blockchain-cli/governance.md, docs/api/blockchain-cli/key-management.md, docs/api/blockchain-cli/payment.md, docs/api/blockchain-cli/validator-staking.md
=> docs: refine cli commands

docs/api/sp-cli.md
Update sp command line doc.
N/A
=> docs: update sp command line doc

docs/sdks/sdk-js.md
=> edit js sdk tutorial

docs/api/blockchain-cli/README.md, docs/guide/greenfield-blockchain/run-node/become-validator.md, docs/guide/storage-provider/run-book/join-SP-network.md
Fix several typo issues.
Make the documents more readable.
=> fix some typo issue

docs/guide/greenfield-blockchain/run-node/run-challenger.md
Update challenger docs  
To ensure that the details are updated and relevant
=> chore: update challenger docs

docs/guide/greenfield-blockchain/run-node/run-relayer.md
Enrich Mainnnet config for relayer
=> docs: fix relayer doc

docs/tutorials/dapp/quick-start.mdx
This pr is to update the `quick-start` chapter
To keep align with mainnet version
=> docs: update quick-start tutorial

docs/faq/greenfield-faqs.md, docs/guide/greenfield-blockchain/modules/billing-and-payment.md, docs/guide/introduction/overview.md
Currently, there is a lack of proper guidance in the documentation to direct users to the price calculator. Therefore, this pull request aims to enhance the user experience by incorporating references to the price calculator in the overview and billing module sections.
There are no other impacts. The UI changes in dcellar might cause links to become invalid, requiring long-term maintenance.
=> docs: add price calculator in multi place

sidebars.js
=> add python sdk

docs/guide/storage-provider/run-book/config.md
Add challenge v2 api rate limite conf.
N/A.
=> docs: add challenge v2 api rate limite conf

docs/guide/getting-started/token-transfer.md
=> feat: add large transfer unlock doc

docs/guide/getting-started/token-transfer.md
modify description about large token transfer
=> chore: modify timelock desc

docs/tutorials/data-marketplace/contract-list.md
update deployment on opbnb testnet
=> feat: update deployment on opbnb testnet

docs/api/storage-provider-rest/get_bucket_meta.md, docs/api/storage-provider-rest/get_user_buckets.md, docs/api/storage-provider-rest/list_buckets_by_ids.md
update metadata bucket storage size docs for
```
GfSpGetUserBuckets
GfSpGetBucketMeta
GfSpListBucketsByIDs
```
=> docs: metadata bucket storage size

docs/guide/greenfield-blockchain/modules/cross-chain.md
=> docs: opBNB crosschain explanation

docs/guide/storage-provider/run-book/config.md
=> docs: sp adds probe config

docs/guide/storage-provider/run-book/join-SP-network.md
Update join SP network doc with recover sp objects command line tool.
Let users understand more about command tools available.
=> feat: recover sp objects intro

docs/guide/greenfield-blockchain/run-node/run-challenger.md
add configs for running challenger
add new config
=> docs: add configs for running challenger

docs/guide/greenfield-blockchain/run-node/run-relayer.md
Instruction for  running relayer for opBNB crosschain
=> docs: run relayer for opBNB crosschain

README.md, docs/guide/storage-provider/run-book/join-SP-network.md
add docs for sp to claim income
add docs
=> docs: add docs for sp to claim income

docs/guide/storage-provider/run-book/run-SP-node.md
docs: add a sample nginx config file for cors configuration
=> docs: add a sample nginx config file for cors configuration

docs/api/storage-provider-rest/list_object_policies.md, sidebars.js
docs: update list object policies
N/A
=> docs: update list object policies

docs/guide/core-concept/cross-chain/contract-list.md, docs/guide/core-concept/cross-chain/interface.md, docs/guide/core-concept/cross-chain/mirror.md, docs/guide/core-concept/cross-chain/sdk.md, sidebars.js
Add opBNB as part of cross-chain sections
=> update terms in cross-chain section

docs/tutorials/data-marketplace/contract-list.md
update deployment on opbnb mainnet
=> feat: update deployment on opbnb mainnet

docs/guide/greenfield-blockchain/run-node/run-relayer.md, docs/release-notes/releaseNotes.md
=> docs: opBNB relayer doc updated

docs/tutorials/ai/hugging-face-intro.md, sidebars.js
add a tutorial about how to use Greenfield for Hugging Face
=> add hugging face tutorial

docs/guide/greenfield-blockchain/modules/storage-module.md
This pr is to update the info of storage module's msgs
To keep align with the latest version of greenfield
=> docs: update msgs of storage module

docs/guide/storage-provider/introduction/workflow.md, docs/guide/storage-provider/run-book/config.md
=> chore: refine sp workflow and config

docs/guide/storage-provider/run-book/common-issues.md, docs/guide/storage-provider/run-book/config.md
chore: update block_syncer and ratelimiter config
N/A
=> chore: update block_syncer and ratelimiter config

docs/guide/storage-provider/run-book/infra-deployment/alibaba/Alibaba Cloud BNB Greenfield RunbookV2.4 English Version.md
add Alibaba Cloud BNB Greenfield RunbookV2.4 English Version.md
=> Create Alibaba Cloud BNB Greenfield RunbookV2.4 English Version.md

docs/tutorials/dapp/nft-migration/overview.md, docs/tutorials/dapp/nft-storage/overview.md, sidebars.js
add a guideline about how to mint/migrate NFT to greenfield
=> add nft migration guideline

docs/release-notes/roadmap.md
=> change upgrade date info

docs/sdks/sdk-js.mdx, docs/sdks/sdks.md
=> chore(docs): Update JS Example

docusaurus.config.js, package.json, yarn.lock
=> feat: Gtag

docusaurus.config.js, package.json, yarn.lock
=> fix: Docrarus url

docs/guide/greenfield-blockchain/modules/storage-module.md
This pr is to update msg fields to keep align with latest greenfield version
Update msg fields
=> docs: remove tags field

docs/guide/storage-provider/run-book/common-issues.md
=> add new issue

docs/guide/storage-provider/run-book/run-SP-node.md
update a best practise for nginx config
If SP's nginx uses proxy_pass directive to pass a request to a proxied server (e.g. the SP gateway microservice), SP need also use proxy_set_header to set the HOST header.
=> chore: update a best practise for nginx config

docusaurus.config.js
This PR enable the sitemap for the doc site.
None
=> doc: add sitemap plugin

docs/tutorials/ai/hugging-face-intro.md, docs/tutorials/dapp/overview.md, docs/tutorials/overview.md, sidebars.js
change link to following:
bsc-testnet: https://greenfield-sp.bnbchain.org/view/marketplace/bsc-testnet.html
opbnb-testnet: https://greenfield-sp.bnbchain.org/view/marketplace/opbnb-testnet.html
No
=> doc: change the data-marketplace link

docs/guide/storage-provider/run-book/common-issues.md, docs/guide/storage-provider/run-book/config.md
=> docs: update sp config

docs/guide/core-concept/cross-chain/interface.md
=> feat: add permission hub interface

docs/guide/core-concept/gas-fees.md, docs/guide/core-concept/storage-provider-lifecycle.md, docs/guide/storage-provider/run-book/exit-SP-network.md, sidebars.js
add docs for sp exit explanation, and guide for sp to conduct exit.
=> docs: sp exit

docs/tutorials/cli/file-management/overview.mdx
=> feat: cmd add task sub commands doc

docs/tutorials/ai/glacier-db-tutorial.md
=> docs: update glacier-db-tutorial

docs/tutorials/cli/file-management/overview.mdx
Add note for get object with sp endpoint.
Add new flag for get object speed optimization.
=> feat: add note for get object with sp endpoint

docs/guide/core-concept/simple-storage-service.md
add a description of object name restrictions.
N/A
=> fix: special object rules

docs/guide/core-concept/cross-chain/contract-list.md
update PermissionHub contracts
=> feat: update permissionHub contracts

docs/guide/getting-started/get-started-dev.md
=> add tooling page

docs/tutorials/get-started/transitioning-from-s3-to-greenfield.md
=> fix: change title name

docs/tutorials/get-started/transitioning-from-s3-to-greenfield.md
=> fix: Indentation

docs/sdks/sdk-js.mdx, docs/tutorials/app/file-management/js-file-managemet.mdx
* Update file-management(JS) docs
* Update JS SDK docs
...
=> docs: Update JS SDK docs

docs/api/storage-provider-rest/put_object.md, docs/api/storage-provider-rest/resumable_put_object.md, docs/guide/storage-provider/modules/common/proto.md, docs/guide/storage-provider/modules/common/task.md, docs/guide/storage-provider/modules/spdb.md
=> feat: agent upload doc

docs/api/storage-provider-rest/query_bucket_read_quota.md, docs/faq/storage-faqs.md, docs/guide/storage-provider/modules/spdb.md, docs/guide/storage-provider/run-book/config.md
add a description of monthly free quota
=> feat: monthly free quota

docs/api/bundle-service.md
Add bundle service endpoint for Greenfield mainnet
NA
=> add mainnet bundle service endpoint

docs/tutorials/app/data-marketplace/overview.md, docs/tutorials/app/file-management/batch-upload.md, sidebars.js
=> add AI category

docs/api/blockchain-cli/validator-staking.md, docs/guide/storage-provider/run-book/common-issues.md, docs/guide/storage-provider/run-book/join-SP-network.md
add a description for the following 2 topics:
1. How much should new SP deposit into their funding address and operator address?
2. What's the unit when checking SP incomes
=> fix: add desc for newly joined sp about funding and income

docs/api/blockchain-cli/storage.md, docs/guide/core-concept/billing-payment.md, docs/guide/greenfield-blockchain/modules/billing-and-payment.md
This pr will add docs for the paymaster feature. 
You can refer to https://github.com/bnb-chain/BEPs/pull/362.
Add docs for paymaster
=> feat: add paymaster doc
